# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonLocalCamera = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLocalCamera.setGeometry(QtCore.QRect(10, 10, 211, 31))
        self.pushButtonLocalCamera.setObjectName("pushButtonLocalCamera")
        self.pushButtonConnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonConnect.setEnabled(False)
        self.pushButtonConnect.setGeometry(QtCore.QRect(230, 10, 211, 31))
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 50, 1941, 531))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutConference = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutConference.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutConference.setHorizontalSpacing(2)
        self.gridLayoutConference.setVerticalSpacing(1)
        self.gridLayoutConference.setObjectName("gridLayoutConference")
        self.lineEditConnectionIP = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditConnectionIP.setEnabled(False)
        self.lineEditConnectionIP.setGeometry(QtCore.QRect(450, 10, 181, 31))
        self.lineEditConnectionIP.setObjectName("lineEditConnectionIP")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skllat"))
        self.pushButtonLocalCamera.setText(_translate("MainWindow", "Включить камеру"))
        self.pushButtonConnect.setText(_translate("MainWindow", "Подключиться"))
        self.lineEditConnectionIP.setPlaceholderText(_translate("MainWindow", "127.0.0.1"))
