arch: mobilenet # MobileNet V1
widen_factor: 0.5
checkpoint_fp: modules/TDDFA_V2/weights/mb05_120x120.pth
bfm_fp: modules/TDDFA_V2/configs/bfm_noneck_v3.pkl # or configs/bfm_noneck_v3_slim.pkl
size: 120
num_params: 62